# from engine import Matrix
import json
import warnings

from sympy import Symbol, lambdify

from . import engine
from .composer import *
from .func import *


def can_use_rust():
    return engine.lib.is_valid


def compile_evaluator(
    evaluator,
    ty="native",
    use_simd=True,
    use_simd512=False,
    opt_level=2,
    dtype="float64",
    num_params=1,
    simd_branch=False,
):
    """Compiles an Evaluator object generated by Symbolica.

    Parameters
    ==========

    ty: target architecture. Options are:
        * "amd": generates x86-64 instructions (amd-sse or amd-avx) depending on the processor.
        * "amd-sse": generates x86-64 SSE2 instructions.
        * "amd-avx": generates x86-64 AVX instrcutions.
        * "arm": generates arm aarch64 instructions.
        * "riscv": generates 64-bit RISC-V instructions.
        * "native" (default): selects the correct mode based on the processor.
        * "bytecode": not supported by the Symbolica bridge.
        * "debug": : not supported by the Symbolica bridge.
    backend (default `rust`): should be `rust`.
    dtype (default `float64`): the data type. Possibilities are `float64` and `complex128`.
    use_simd (default `True`): generates SIMD code for vectorized operations. Currently supports
        AVX on x86-64 and NEON on aarch64 systems.
    opt_level (default 2): optimization level (0, 1, 2, or 3). Broadly the numbers are parallel to -O0, -O1, -O2, and -O3
        options to gcc and clang. Level-0 performs minimum amount of optimization. Level-1 does peephole optimization.
        Levels 2 and 3 use improved graph-coloring algorithms for better register allocation.

    ==> returns a `SymbolicaFunc` object. The user can use `evaluate` and `evaluate_complex` functions to
        call the compiled code.

    >>> import numpy as np
    >>> from symbolica import *
    >>> from symjit import compile_evaluator
    >>>
    >>> x, y = S("x"), S("y")
    >>> e = E("x + y^2").evaluator({}, {}, [x, y])
    >>> f = compile_evaluator(e)
    >>>
    >>> X = np.array([[4.0, 10.0]])
    >>> assert e.evaluate(X) == f.evaluate(X)
    """
    if not can_use_rust():
        raise ValueError("unsupported platform")

    if isinstance(evaluator, str):
        model = evaluator
    else:
        model = str(evaluator.get_instructions())

    return SymbolicaFunc(
        model,
        ty=ty,
        use_simd=use_simd,
        use_simd512=use_simd512,
        opt_level=opt_level,
        dtype=dtype,
        num_params=num_params,
        simd_branch=simd_branch,
    )


def compile_composer(
    composer,
    ty="native",
    dtype="float64",
    use_simd=True,
    use_simd512=False,
    opt_level=2,
    simd_branch=True,
):
    """Compiles a Composer object.

    Parameters
    ==========

    ty: target architecture. Options are:
        * "amd": generates x86-64 instructions (amd-sse or amd-avx) depending on the processor.
        * "amd-sse": generates x86-64 SSE2 instructions.
        * "amd-avx": generates x86-64 AVX instrcutions.
        * "arm": generates arm aarch64 instructions.
        * "riscv": generates 64-bit RISC-V instructions.
        * "native" (default): selects the correct mode based on the processor.
        * "bytecode": not supported by the Symbolica bridge.
        * "debug": : not supported by the Symbolica bridge.
    dtype (default `float64`): the data type. Possibilities are `float64` and `complex128`.
    use_simd (default `True`): generates SIMD code for vectorized operations. Currently supports
        AVX on x86-64 and NEON on aarch64 systems.
    opt_level (default 2): optimization level (0, 1, 2, or 3). Broadly the numbers are parallel to -O0, -O1, -O2, and -O3
        options to gcc and clang. Level-0 performs minimum amount of optimization. Level-1 does peephole optimization.
        Levels 2 and 3 use improved graph-coloring algorithms for better register allocation.

    ==> returns a `SymbolicaFunc` object. The user can use `evaluate` and `evaluate_complex` functions to
        call the compiled code.

    >>> import numpy as np
    >>> from symbolica import *
    >>> from symjit import compile_evaluator
    >>>
    >>> x, y = S("x"), S("y")
    >>> e = E("x + y^2").evaluator({}, {}, [x, y])
    >>> f = compile_evaluator(e)
    >>>
    >>> X = np.array([[4.0, 10.0]])
    >>> assert e.evaluate(X) == f.evaluate(X)
    """
    if not can_use_rust():
        raise ValueError("unsupported platform")

    model = str(composer.get_instructions())

    return SymbolicaFunc(
        model,
        ty=ty,
        use_simd=use_simd,
        use_simd512=use_simd512,
        opt_level=opt_level,
        dtype=dtype,
        num_params=composer.num_params,
        simd_branch=simd_branch,
    )
